### ISSUE TITLE
Prevent timepicker plugin triggering change on init

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-widget-timepicker#12]
This change on init by the timepicker plugin causes undesirable effects in using this plugin as a filter in yii2-grid (triggers infinite loop on  init and refreshes the grid)... as well as using it as an Editable Plugin kartik-v/yii2-editable#143.

**Comment by kartik-v** [comment]
Resolved via 886656d.

**Comment by vpadhariya** [comment]
Hi @kartik-v , 

I tried update to the latest version but this bug does not get resolved.

For your reference here is my composer.json required section.

"require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "yiisoft/yii2-jui": "~2.0.0",
        "yiisoft/yii2-imagine": "~2.0.0",
        "yiidoc/yii2-redactor": "*",
        "vova07/yii2-fileapi-widget": "*",
        "kartik-v/yii2-widget-growl": "*",
        "kartik-v/yii2-editable": "*",
        "kartik-v/yii2-widget-datepicker": "*",
        "kartik-v/yii2-widget-fileinput": "*",
        "kartik-v/yii2-widget-colorinput": "*",
        "kartik-v/yii2-widget-timepicker": "*",
        "kartik-v/yii2-widget-select2": "^2.0",
        "intelligent/yii2-uikit": "dev-master",
        "2amigos/yii2-file-upload-widget": "~1.0",
        "nterms/yii2-mailqueue": "*",
        "paypal/rest-api-sdk-php": "^1.11"
    }

**Comment by basel-ax** [comment]
Hi. Same problem. I install last version: 
kartik-v/yii2-widget-timepicker v1.0.3
kartik-v/yii2-editable v1.7.6
but this bug still exist. What can i do to solve this problem?

**Comment by dmkdesign** [comment]
Anyone have an answer to this?  Diggin through the code but its over my head.  I'd use the DateTimePicker but I havent found a way to turn off the 'pickDate'  option.

**Comment by baldiri** [comment]
Hi people,

same problem as well. Kartik we need you!!!

**Comment by kartik-v** [comment]
Folks - I will need time to understand what issue you are facing? Please drop in details here on the issue clearly and how to reproduce? Will find time to check this.

**Comment by luiszg** [comment]
Hello, I am researching this issue, and the trouble is when I have a popover option. If I change to 'asPopover' => false, the pjax work correctly.. Someboy hava some solution?
